In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [3]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [4]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [5]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [6]:
l = [1,2,3,4,5]
arr = np.array(l)

In [7]:
arr + 10

array([11, 12, 13, 14, 15])

In [10]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [11]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [13]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [17]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [18]:
A

array([[1, 2],
       [3, 4]])

In [19]:
B

array([[5, 6],
       [7, 8]])

In [20]:
A * B

array([[ 5, 12],
       [21, 32]])

In [21]:
A @ B

array([[19, 22],
       [43, 50]])

In [22]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [23]:
A

array([[1, 2],
       [3, 4]])

In [24]:
A.T

array([[1, 3],
       [2, 4]])

In [25]:
A

array([[1, 2],
       [3, 4]])

In [26]:
B

array([[5, 6],
       [7, 8]])

In [27]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [28]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [31]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [35]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]