In [6]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [8]:
a = [1, 2, 3, "hello"]
a

[1, 2, 3, 'hello']

In [10]:
np.array(a)

array(['1', '2', '3', 'hello'], dtype='<U21')

In [11]:
l = [[1, 2, 3], [4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
arr = np.linspace(1,6,3)
arr

array([1. , 3.5, 6. ])

In [27]:
np.random.rand(10)

array([0.565914  , 0.81815309, 0.26061289, 0.74627392, 0.03082798,
       0.14614554, 0.77358852, 0.17244544, 0.28586591, 0.43958116])

In [28]:
np.random.randn(10)

array([-0.35958519,  0.03074177,  0.49634281,  1.13401102, -2.4305342 ,
        0.10071771,  0.1237391 , -1.11885928, -0.20434028, -0.04833283])

In [29]:
np.random.randint(6)

5

In [30]:
np.random.randint(1,30,10)

array([25, 22, 28, 15, 13,  4,  1, 14,  6, 19], dtype=int32)

In [33]:
arr = np.array([[1, 2, 3], [4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr.shape

(3, 3)

In [35]:
arr.size

9

In [36]:
arr.dtype

dtype('int64')

In [39]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr.min()

np.int64(1)

In [41]:
arr.max()

np.int64(9)

In [42]:
arr.sum()

np.int64(45)

In [43]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [44]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [45]:
arr.mean()

np.float64(5.0)

In [46]:
arr.std()

np.float64(2.581988897471611)

In [47]:
arr.argmax()

np.int64(8)

In [48]:
arr.argmin()

np.int64(0)

In [50]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [53]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])