In [18]:
import numpy as np

In [19]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [20]:
s.sum()

np.int64(405)

In [21]:
b = np.sum(s, axis= 1)
for i in b:
    if i != 45:
        print("sudoku is not valid")
        break
else:
    print("For rows its valid")

For rows its valid


In [22]:
c = np.sum(s, axis= 0)
for i in b:
    if i != 45:
        print("sudoku is not valid")
        break
else:
    print("For columns its valid")

For columns its valid


In [23]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [24]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [25]:
s[0:3,6:]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [26]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [27]:
data.shape

(5, 3)

In [28]:
np.mean(data[:,0])

np.float64(18.4)

In [29]:
data[:,1]

array([85, 92, 76, 65, 90])

In [30]:
np.max(data[:,2])

np.int64(95)

In [31]:
data[data[:,1] > 90]

array([[19, 92, 88]])

In [32]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [33]:
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [34]:
len(data[data[:,0] < 19])

3

In [35]:
np.mean(data[:,1:], axis=0)

array([86.6, 83.2])

In [36]:
data[(data[:,1] >=80) & (data[:,2] >=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [37]:
data[:,2] [data[:,2] < 75] =0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])